/*
**  The different TARGETS that we support
*/
#define	DOS86		100
#define	DOS386		101
#define	WIN16		200
#define	WIN32S		201
#define	UNIX		300

/*
**  The different MACHINES that we support
*/
#define	M_PC		200		/* Intel x86 PC	*/
#define	M_HPUX		201		/* HPUX 9.05	*/
#define	M_SPARC		202		/* SUNOS 4.1.x	*/
#define	M_SOLARIS2	203		/* Solaris 2.4	*/
#define	M_IRIX		204		/* IRIX 5.3		*/
#define	M_AIX		205		/* AIX 4.1		*/
